version: "3.8"

services:
  backend:
    build: .
    depends_on:
      - postgress
      - redis
      - elasticsearch

    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200

    ports:
      - "3000:3000"
    networks:
      - app-network

  # postgress setup
  postgress:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  # redis setup
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  # elasticsearch setup
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    restart: always
    environment:
      discovery.type: single-node
    ports:
      - "9201:9200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
